### ISSUE TITLE
Not detecting all threads on 3900X

### ISSUE THREAD

**Issue by ghost** [xyrus02/apophysis-7x#2]
I have 24 threads but the program only allows me to select up to 12. If it's not a hard limit of the program design, could you increase this limit?

![Capture](https://user-images.githubusercontent.com/20543556/79001599-50834800-7b81-11ea-8bf8-f7d0decce6f2.PNG)

**Comment by xyrus02** [comment]
It's hard coded into the combo box. But there shouldn't be a problem if there are more threads.
Can you try the build in the attachment and tell me if it works fine? Thanks

[Apophysis7x_9ac290fef15e626c5d2abedc77957ffe05080b93.zip](https://github.com/xyrus02/apophysis-7x/files/4462220/Apophysis7x_9ac290fef15e626c5d2abedc77957ffe05080b93.zip)

**Comment by ghost** [comment]
The drop down list goes to 32 and I am able to use 24 cores while rendering now. Seems to work, thanks!
